# Generated by Django 5.1.6 on 2025-02-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReturnBook',
            new_name='ReturnRecord',
        ),
        migrations.RemoveField(
            model_name='borrowingrecord',
            name='return_date',
        ),
    ]
