# Generated by Django 5.1.6 on 2025-02-14 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing_record',
            name='status',
        ),
        migrations.CreateModel(
            name='Borrowed_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('borrowed', 'borrowed'), ('returned', 'returned'), ('available', 'available')], default='available', max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_mgmt.book')),
            ],
        ),
    ]
