# Generated by Django 5.1.6 on 2025-02-14 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_mgmt', '0002_remove_borrowing_record_status_borrowed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed_status',
            name='borrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_mgmt.borrowing_record'),
        ),
    ]
