# Generated by Django 5.1.6 on 2025-02-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_mgmt', '0002_borrowingrecord_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingrecord',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
