# Generated by Django 5.1.6 on 2025-02-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_mgmt', '0003_borrowed_status_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing_record',
            name='status',
            field=models.CharField(choices=[('borrowed', 'borrowed'), ('returned', 'returned'), ('available', 'available')], default='available', max_length=50),
        ),
        migrations.DeleteModel(
            name='Borrowed_Status',
        ),
    ]
