# Generated by Django 5.2 on 2025-04-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_mgmt', '0004_reservation_due_date_alter_borrowingrecord_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingrecord',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='due_date',
            field=models.DateField(),
        ),
    ]
